/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supermarket;

import java.awt.print.PrinterException;
import javax.swing.table.TableModel;

/**
 *
 * @author USER
 */
public class print extends javax.swing.JFrame {

    /**
     * Creates new form print
     */
    public print() {
        initComponents();
    }
    
String lsubtotal;
String lpay;
String lbalance;
    
    
public print(String subtotal, String pay, String balance, TableModel tableModel) throws PrinterException {
    initComponents();
    
    this.lsubtotal = subtotal;
    this.lpay = pay;
    this.lbalance = balance;
    
    StringBuilder receipt = new StringBuilder();
    
    receipt.append("**********************************************\n");
    receipt.append("             BAIUST SUPER MARKET              \n");
    receipt.append("**********************************************\n\n");
    receipt.append(String.format("%-20s %-10s %-6s %-10s\n", "Product", "Price", "Qty", "Total"));
    receipt.append("------------------------------------------------\n");
    
    for (int i = 0; i < tableModel.getRowCount(); i++) {
        String product = (String) tableModel.getValueAt(i, 1);
        String price = (String) tableModel.getValueAt(i, 2);
        String quantity = (String) tableModel.getValueAt(i, 3);
        int total = (int) tableModel.getValueAt(i, 4);
        
        
        if (product.length() > 20) {
            product = product.substring(0, 17) + "...";
        }
        
        
        receipt.append(String.format("%-20s %-10s %-6s %-10d\n", product, price, quantity, total));
    }
    
    receipt.append("\n");
    receipt.append("------------------------------------------------\n");
    receipt.append(String.format("%-30s %s\n", "Subtotal:", subtotal));
    receipt.append(String.format("%-30s %s\n", "Pay:", pay));
    receipt.append(String.format("%-30s %s\n", "Balance:", balance));
    receipt.append("\n");
    receipt.append("************** Thank You **************\n");
    receipt.append("************ Visit Us Again ************\n");
    receipt.append("****************************************\n");
    
    textprint.setText(receipt.toString());
    textprint.print();
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textprint = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textprint.setColumns(20);
        textprint.setRows(5);
        jScrollPane1.setViewportView(textprint);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new print().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textprint;
    // End of variables declaration//GEN-END:variables
}
